Repository small-doggy-watching-you/PuppyBox, pull requests merged in 2025-07, with the labels that each got.

#6 #2 로그인 화면 UI구성
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Scenes/Login/LoginViewController.swift
Labels: feat

#10 Feat/#9 image path
  PuppyBox/Models/ImageSize.swift
  PuppyBox/Models/MovieData.swift
  PuppyBox/Utils/DummyService.swift
  PuppyBox/Utils/ImagePathService.swift
  PuppyBox/Utils/Secrets.swift
Labels: feat

#12 로그인 로직 구현 / 이미지패스 서비스 리팩토링
  PuppyBox/Models/CoreData/CoreDataManager.swift
  PuppyBox/Models/ImageSize.swift
  PuppyBox/Models/TestData/UserDummyData.swift
  PuppyBox/Models/UserSetting.swift
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Utils/DummyService.swift
  PuppyBox/Utils/ImagePathService.swift
Labels: feat, refactor

#11 Feat/#1 movie list view controller
  PuppyBox.xcodeproj/project.pbxproj
  PuppyBox.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Models/MovieData.swift
  PuppyBox/Resources/Secrets.plist
  PuppyBox/Scenes/MovieList/MainTabBarController.swift
  PuppyBox/Scenes/MovieList/MovieListViewController.swift
  PuppyBox/Scenes/MovieList/MovieListViewModel.swift
  PuppyBox/Scenes/MovieList/MoviePosterCell.swift
  PuppyBox/Scenes/MovieList/MovieSectionHeader.swift
  PuppyBox/Scenes/MovieList/SearchViewController.swift
  PuppyBox/Scenes/MyPage/MyPageViewController.swift
  PuppyBox/Utils/DataService.swift
Labels: add, feat

#32 #31 fix: gitignore 수정
  .gitignore
Labels: fix

#34 #33 fix: git tracking에서 xcshareddata 삭제
  PuppyBox.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: fix

#21 Feat/#17 영화 포스터이미지 + 상세정보 뷰 까지 구현
  PuppyBox.xcodeproj/xcuserdata/housedone.xcuserdatad/xcschemes/xcschememanagement.plist
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Resources/Assets.xcassets/AppIcon.appiconset/PuppyBox-macOS-Dark-1024x1024.png
  PuppyBox/Scenes/MovieDetail/FullScreenImageOverlayView.swift
  PuppyBox/Scenes/MovieDetail/GenreMap.swift
  PuppyBox/Scenes/MovieDetail/MovieDetailView.swift
  PuppyBox/Scenes/MovieDetail/MovieDetailViewController.swift
  PuppyBox/Scenes/MovieDetail/MovieDetailViewModel.swift
  PuppyBox/Scenes/MovieDetail/MovieInfoView.swift
Labels: add, chore, feat, fix, refactor

#29 회원가입 로직 구현
  PuppyBox/Models/CoreData/CoreDataManager.swift
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/SignUp/SignUpViewController.swift
  PuppyBox/Utils/AlertFactory.swift
Labels: feat

#35 Feat: #17- 영화상세정보뷰컨트롤러에서 Alamofire 사용하던 부분 Kingfisher 사용하도록 변경, Refac…
  PuppyBox.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PuppyBox/Scenes/MovieDetail/FullScreenImageOverlayView.swift
  PuppyBox/Scenes/MovieDetail/MovieBookingView.swift
  PuppyBox/Scenes/MovieDetail/MovieDetailView.swift
  PuppyBox/Scenes/MovieDetail/MovieDetailViewController.swift
  PuppyBox/Scenes/MovieDetail/MovieInfoView.swift
Labels: fix, refactor

#38 Feat/#30 my page view
  PuppyBox/Models/MyMovie.swift
  PuppyBox/Models/TestData/UserDummyData.swift
  PuppyBox/Models/UserData.swift
  PuppyBox/Resources/Assets.xcassets/defaultProfile.imageset/Contents.json
  PuppyBox/Resources/Assets.xcassets/defaultProfile.imageset/british-shorthair-9717301_1280.jpg
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/MovieList/MainTabBarController.swift
  PuppyBox/Scenes/MyPage/MovieCell.swift
  PuppyBox/Scenes/MyPage/MyPageViewController.swift
  PuppyBox/Scenes/MyPage/MyPageViewModel.swift
  PuppyBox/Scenes/MyPage/SectionHeader.swift
  PuppyBox/Scenes/MyPage/UserInfoCell.swift
Labels: feat

#43 feat: 영화 눌렀을 때 상세 페이지로 이동
  PuppyBox/Scenes/MovieList/MovieListViewController.swift
Labels: feat

#46 Chore/#39 오토레이아웃 수정
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Extensions/UIFont++.swift
  PuppyBox/Resources/Fonts/PlusJakartaSans-Bold.ttf
  PuppyBox/Resources/Fonts/PlusJakartaSans-Medium.ttf
  PuppyBox/Resources/Fonts/PlusJakartaSans-Regular.ttf
  PuppyBox/Resources/Fonts/PlusJakartaSans-SemiBold.ttf
  PuppyBox/Resources/Info.plist
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/MyPage/MovieCell.swift
  PuppyBox/Scenes/MyPage/MyPageViewController.swift
  PuppyBox/Scenes/MyPage/SectionHeader.swift
  PuppyBox/Scenes/MyPage/UserInfoCell.swift
  PuppyBox/Scenes/SignUp/SignUpViewController.swift
Labels: chore

#48 Feat/#47 마이페이지에서 코어데이터 읽어오기
  PuppyBox/Models/CoreData/Account+CoreDataClass.swift
  PuppyBox/Models/CoreData/Account+CoreDataProperties.swift
  PuppyBox/Models/CoreData/CoreDataManager.swift
  PuppyBox/Models/CoreData/Reservation+CoreDataClass.swift
  PuppyBox/Models/CoreData/Reservation+CoreDataProperties.swift
  PuppyBox/Models/CoreData/WatchedMovie+CoreDataClass.swift
  PuppyBox/Models/CoreData/WatchedMovie+CoreDataProperties.swift
  PuppyBox/Models/TestData/UserDummyData.swift
  PuppyBox/Models/UserData.swift
  PuppyBox/Resources/Assets.xcassets/adminProfile.imageset/Contents.json
  PuppyBox/Resources/Assets.xcassets/adminProfile.imageset/adminProfile.jpg
  PuppyBox/Resources/PuppyBox.xcdatamodeld/PuppyBox.xcdatamodel/contents
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/MyPage/MovieCell.swift
  PuppyBox/Scenes/MyPage/MyPageViewController.swift
  PuppyBox/Scenes/MyPage/MyPageViewModel.swift
  PuppyBox/Scenes/MyPage/SectionHeader.swift
  PuppyBox/Scenes/MyPage/UserInfoCell.swift
  PuppyBox/Utils/DateFormat.swift
Labels: feat

#52 ViewModel로 데이터 필터링 로직 이동
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Scenes/MovieList/MovieListViewModel.swift
  PuppyBox/Scenes/MovieList/SearchViewController.swift
Labels: refactor

#54 refector: CollectionView 제약에서 SafeArea 제거
  PuppyBox/Scenes/MovieList/SearchViewController.swift
Labels: refactor

#56 Chore/#55 add UI color
  PuppyBox/Extensions/UIColor+AppColors.swift
  PuppyBox/Scenes/MyPage/SectionHeader.swift
Labels: chore

#63 Feat/#62 회원가입 화면 키보드 다운
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/SignUp/SignUpViewController.swift
Labels: feat

#66 add: 앱 실행 시 애니메이션 구현
  PuppyBox/App/Base.lproj/LaunchScreen.storyboard
  PuppyBox/App/Base.lproj/Main.storyboard
  PuppyBox/App/SceneDelegate.swift
  PuppyBox/Scenes/Splash/SplashViewController.swift
Labels: add

#67 Add/#65 search result nil
  PuppyBox/Scenes/MovieList/SearchViewController.swift
  PuppyBox/Scenes/Splash/SplashViewController.swift
Labels: add

#71 Fix/#68 상세정보 뷰의 풀스크린 이미지 오버레이뷰의 우측 최상단에 보여지는 닫기 버튼을 포스터 아래 중앙에 위치시키는 것으로 수정
  PuppyBox/Scenes/MovieDetail/FullScreenImageOverlayView.swift
Labels: fix

#74 Chore/#61 주석 및 코드정리
  PuppyBox/Models/CoreData/CoreDataManager.swift
  PuppyBox/Models/ImageSize.swift
  PuppyBox/Models/MyMovie.swift
  PuppyBox/Models/TestData/UserDummyData.swift
  PuppyBox/Models/UserData.swift
  PuppyBox/Scenes/Login/LoginViewController.swift
  PuppyBox/Scenes/MyPage/MovieCell.swift
  PuppyBox/Scenes/MyPage/MyPageSectionHeader.swift
  PuppyBox/Scenes/MyPage/MyPageViewController.swift
  PuppyBox/Scenes/MyPage/MyPageViewModel.swift
  PuppyBox/Scenes/MyPage/UserInfoCell.swift
  PuppyBox/Scenes/SignUp/SignUpViewController.swift
Labels: chore

#73 Chore: #70- 티켓 뷰 보여지는 부분 수정
  PuppyBox/Scenes/MovieDetail/Ticket/TicketViewController.swift
Labels: chore
